name: Deployment pipeline

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: PNPM
        run: corepack enable pnpm
      - name: Install dependens
        run: npm ci
      # - name: Lint
      #   run: npm run eslint
      # - name: Build
      #   run: npm run build
      - name: Test
        run: npm run test
      - name: E2E test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:8080